version: '{build}'
environment:
  FIREBASE_TOKEN:
    secure: Cg7gy+/CqosOmi07q9CaXiF2QIWnA5+gyyQExQ+bKh2XNAqwjLifr5EPtC3w4w3d
install:
- cmd: |
    cinst docfx --version 2.12.1
    if not exist "./node_modules" yarn install --pure-lockfile --ignore-optional
build_script:
- cmd: yarn run deploy
cache:
    - node_modules -> package.json
test: off
