version: '{build}'
environment:
  FIREBASE_TOKEN:
    secure: tt/4l9UhbDPV4uWGleQkEzXKih1Z4KDaXKhk5kqE2PanYbdV44wLFiENtsHwpCBW
install:
- cmd: |
    cinst docfx -y
    if not exist "./node_modules" yarn install --pure-lockfile --ignore-optional
build_script:
- ps: |
    yarn run build
    firebase deploy
cache:
    - node_modules -> package.json
test: off
