version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
environment:
  build_user: JeremyTCD
  build_user_email: jeremytanchongdao@gmail.com
  github_token:
    secure: +gVDTXWK1k+HQj8CZfBIzSnP/Y5RvoaXmuByOSir0MRSAW+eYRpjTrcXA0F/2k6r
  cloudflare_token:
    secure: rjtyHGd5hWIQ/8/adaQ/ErTrbH9QAcEpEiqfKx/l9djExiBtEOFbj9PnA+lH5qJk
install:
- ps: | 
    cinst docfx -y
    Install-Product node 8.9.1 x64
- cmd: if not exist "./node_modules" yarn install
build_script:
- ps: |
    yarn run build-production
    
    # Set Github credentials
    git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
    git config --global user.email $env:build_user_email
    git config --global user.name $env:build_user
    
    # Clone current static files, replace all of them with the new site
    git clone https://github.com/JeremyTCD/JeremyTCD.github.io.git -b master origin_site -q
    Copy-Item origin_site/.git bin/_site -recurse
    
    # Commit and push
    CD bin/_site
    git add -A 2>&1
    git commit -m "CI Updates" -q
    git push origin master -q

    # Purge Cloudflare cache
    $headers = @{"X-Auth-Email"="$env:build_user_email"; "X-Auth-Key"="$env:cloudflare_token";}
    $body = ConvertTo-Json @{"purge_everything"=$true;}
    Invoke-RestMethod -Method DELETE -Uri https://api.cloudflare.com/client/v4/zones/3bba4bf59e182130f215856cac02c810/purge_cache/ -Headers $headers -Body $body
cache:
    - node_modules -> package.json
test: off